/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://t5i7cgblwberrk5ih2dgmpfzgm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-26kklo3755f5pdu5hicby7zx4q",
    "aws_cognito_identity_pool_id": "us-east-2:7faa6dcf-c8e0-4950-a01f-d9e1bffe7608",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ew9ky6nzA",
    "aws_user_pools_web_client_id": "fkdin9kg6etjs9q1d9oflmsbi",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    }
};


export default awsmobile;
