/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://fippgfcj4fh6bdlnxilfql3yry.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_apiKey": "da2-wx6jzvcarbamliynxxeyuzwczi",
    "aws_appsync_authenticationType": "API_KEY"
};


export default awsmobile;
